project:
  type: website
  output-dir: docs

website:
  title: "Diego Martín-Álvarez"
  site-url: https://dmartinalv.github.io
  navbar:
    search: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Curriculum Vitae"
        href: curriculum.qmd

format:
  html:
    theme:
        light: flatly
        dark: darkly
    css: styles.css
    toc: true
    
editor: visual